apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jyothi-ingress
  namespace: jquery
spec:
  rules:
  - host: jquery.jyothirreddy.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jyothi-service
            port:
              number: 80

              
